-- write your solution here
SELECT
    (SELECT CAR FROM footer_values WHERE CAR IS NOT NULL ORDER BY ID DESC LIMIT 1)    AS CAR,
    (SELECT LENGTH FROM footer_values WHERE LENGTH IS NOT NULL ORDER BY ID DESC LIMIT 1) AS LENGTH,
    (SELECT WIDTH FROM footer_values WHERE WIDTH IS NOT NULL ORDER BY ID DESC LIMIT 1)  AS WIDTH,
    (SELECT HEIGHT FROM footer_values WHERE HEIGHT IS NOT NULL ORDER BY ID DESC LIMIT 1) AS HEIGHT;


SELECT 
    FIRST_VALUE(CAR) OVER (ORDER BY (CAR IS NOT NULL) DESC, ID DESC) AS CAR,
    FIRST_VALUE(LENGTH) OVER (ORDER BY (LENGTH IS NOT NULL) DESC, ID DESC) AS LENGTH,
    FIRST_VALUE(WIDTH) OVER (ORDER BY (WIDTH IS NOT NULL) DESC, ID DESC) AS WIDTH,
    FIRST_VALUE(HEIGHT) OVER (ORDER BY (HEIGHT IS NOT NULL) DESC, ID DESC) AS HEIGHT
FROM footer_values
LIMIT 1;  