# -*- coding: utf-8 -*-
"""Sales_trend_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKvOKGIYJAWo47geHn85LsYjIU82Go-2
"""

import numpy as np
import pandas as pd

df = pd.read_csv("sales_data.csv")
df.head()

df = pd.read_csv(
    "sales_data.csv",
    engine="python",
    header=None,
    names=[
        "Order ID",
        "Product",
        "Quantity Ordered",
        "Price Each",
        "Order Date",
        "Street",
        "City",
        "State Zip"
    ]
)

df.head()

df = df.iloc[1:].reset_index(drop=True)
df.head()

df["Purchase Address"] = (
    df["Street"].astype(str) + ", " +
    df["City"].astype(str) + ", " +
    df["State Zip"].astype(str)
)
df.head()

df = df[
    [
        "Order ID",
        "Product",
        "Quantity Ordered",
        "Price Each",
        "Order Date",
        "Purchase Address"
    ]
]
df.head()

df["Quantity Ordered"] = pd.to_numeric(df["Quantity Ordered"], errors="coerce")
df["Price Each"] = pd.to_numeric(df["Price Each"], errors="coerce")

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%m/%d/%y %H:%M",
    errors="coerce"
)
df.head()

df["Price Each"] = df.groupby("Product")["Price Each"].transform(lambda x: x.fillna(x.mean()))
df.head()

df["Month"] = df["Order Date"].dt.to_period("M")
df.head()

df["Total Sales"] = df["Quantity Ordered"] * df["Price Each"]
df.head()

monthly_revenue = df.groupby("Month")["Total Sales"].sum()
monthly_revenue_df = monthly_revenue.reset_index()
monthly_revenue_df

best_product = (
    df.groupby(["Month", "Product"])["Quantity Ordered"]
    .sum()
    .reset_index()
    .sort_values(["Month", "Quantity Ordered"], ascending=[True, False])
    .drop_duplicates("Month")
    .set_index("Month")["Product"]
)
best_product_df = best_product.reset_index()
best_product_df.columns = ["Month", "Product"]
best_product_df